export const actionTypes = {
    GET_PRODUCTS: "GET_PRODUCTS",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    SET_MESSAGE : "SET_MESSAGE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE",
    GET_PROFILE: "GET_PROFILE"
}